package com.dbx.dialect.api;

import static com.dbx.dialect.api.MappingCase.PAIR;
import static com.dbx.dialect.api.MappingCase.supported;
import static com.dbx.dialect.api.SourceColumns.column;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.function.Supplier;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * {@code target.ddlPlan} (obligation 24): ADR-0011's minimal writable table and nothing more, with values
 * rendered only by the target dialect's typed literal renderer (ADR-0008 §Plans as amended by #123).
 * PostgreSQL 15 execution of this DDL is proven at L2 by {@code contract} slice 8, not here.
 */
class TargetDialectContractTest {

    private static final TargetType BIGINT = new TargetType(TargetTypeName.BIGINT, List.of());
    private static final TargetType TEXT = new TargetType(TargetTypeName.TEXT, List.of());
    private static final TargetType NUMERIC_20_0 = new TargetType(TargetTypeName.NUMERIC, List.of(20, 0));
    private static final TargetType NUMERIC_10_2 = new TargetType(TargetTypeName.NUMERIC, List.of(10, 2));
    private static final TargetType TIMESTAMP_3 = new TargetType(TargetTypeName.TIMESTAMP, List.of(3));
    private static final TargetType VARCHAR_64 = new TargetType(TargetTypeName.VARCHAR, List.of(64));

    // --- Plan shape and exact text (ADR-0008 §Plans; ADR-0011 §DDL) ---------------------------------

    @Test
    void theDdlPlanHasTheTargetDdlShape() {
        SqlPlan plan = PAIR.target().ddlPlan(orders());

        assertEquals(OperationKind.TARGET_DDL, plan.operationKind(), "obligation 24: one TARGET_DDL plan");
        assertEquals(TimeoutClass.DDL, plan.timeoutClass(), "ADR-0008 §Plans: DDL runs under the DDL timeout class");
        assertEquals(Set.of(RequiredPrivilege.TARGET_CREATE_IN_SCHEMA), plan.requiredPrivileges(),
                "ADR-0006: creating a table and its owned sequence needs CREATE in the schema, nothing more");
        assertEquals(EvidencePolicy.STATEMENT_ONLY, plan.evidencePolicy(),
                "ADR-0008 §Plans: DDL returns no rows, so the evidence is the statements");
        assertEquals(ResultSchema.NONE, plan.resultSchema(), "ADR-0008 §Plans: DDL declares that it returns no result");
        for (ParameterizedStatement statement : plan.statements()) {
            assertEquals(List.of(), statement.parameters(),
                    "ADR-0008 §Plans as amended by #123: PostgreSQL binds nothing in DDL, so values are literals");
        }
    }

    @Test
    void theStatementsArePinnedForARepresentativeTable() {
        assertEquals(List.of(
                        "CREATE SEQUENCE \"shop\".\"orders_id_seq\" AS bigint",
                        "CREATE TABLE \"shop\".\"orders\" ("
                                + "\"id\" numeric(20,0) NOT NULL DEFAULT nextval(E'\"shop\".\"orders_id_seq\"'::regclass), "
                                + "\"status\" text NOT NULL DEFAULT E'new' CHECK (\"status\" IN (E'new', E'paid')), "
                                + "\"total\" numeric(10,2) DEFAULT 0.00, "
                                + "\"created_at\" timestamp(3) without time zone NOT NULL DEFAULT LOCALTIMESTAMP(3), "
                                + "PRIMARY KEY (\"id\"))",
                        "ALTER SEQUENCE \"shop\".\"orders_id_seq\" OWNED BY \"shop\".\"orders\".\"id\""),
                sql(PAIR.target().ddlPlan(orders())),
                "ADR-0011 §DDL; TP §7.3: columns, exact types, NOT NULL, owned sequence, ENUM CHECK, whitelisted "
                        + "defaults and the primary key, and nothing else");
    }

    @Test
    void anIntegerAutoIncrementIsAnIdentityAndATableWithoutKeyHasNone() {
        TargetTable identity = table(List.of(
                        new TargetColumn(id("id"), BIGINT, Nullability.NOT_NULL, Optional.empty(),
                                IdentityIntent.IDENTITY_BY_DEFAULT, List.of()),
                        new TargetColumn(id("name"), VARCHAR_64, Nullability.NULLABLE)),
                List.of(id("id")));
        TargetTable keyless = table(List.of(new TargetColumn(id("name"), VARCHAR_64, Nullability.NULLABLE)), List.of());

        assertEquals(List.of("CREATE TABLE \"shop\".\"orders\" (\"id\" bigint NOT NULL GENERATED BY DEFAULT AS "
                        + "IDENTITY, \"name\" varchar(64), PRIMARY KEY (\"id\"))"),
                sql(PAIR.target().ddlPlan(identity)),
                "TP §7.3: an integer auto-increment is GENERATED BY DEFAULT AS IDENTITY, in one statement");
        assertEquals(List.of("CREATE TABLE \"shop\".\"orders\" (\"name\" varchar(64))"),
                sql(PAIR.target().ddlPlan(keyless)),
                "TP §7.3: a table without an approved key gets no PRIMARY KEY");
    }

    @Test
    void aNumeric20OwnedSequenceIsCreatedThenUsedThenOwnedInThatOrder() {
        List<String> statements = sql(PAIR.target().ddlPlan(orders()));

        assertEquals(3, statements.size(), "TP §7.3: sequence, table, ownership");
        assertTrue(statements.get(0).startsWith("CREATE SEQUENCE ") && statements.get(0).endsWith(" AS bigint"),
                "TP §7.3: the owned sequence is bigint and exists before the table that defaults to it");
        assertTrue(statements.get(1).startsWith("CREATE TABLE ")
                        && statements.get(1).contains("DEFAULT nextval(E'\"shop\".\"orders_id_seq\"'::regclass)"),
                "TP §7.3: the numeric(20,0) column defaults to nextval on the sequence's regclass");
        assertTrue(statements.get(2).startsWith("ALTER SEQUENCE ") && statements.get(2).contains(" OWNED BY "),
                "TP §7.3: ownership comes last, once the owning column exists");
    }

    @Test
    void currentTimestamp6BecomesLocalTimestamp3() {
        Supported datetime6 = supported(column("datetime", "datetime(6)").datetimePrecision(6).notNull()
                .columnDefault("CURRENT_TIMESTAMP(6)"), MappingOptions.DEFAULTS);
        int mapped = datetime6.targetType().modifiers().get(0);
        TargetTable table = table(List.of(new TargetColumn(id("created_at"), datetime6.targetType(),
                Nullability.NOT_NULL, Optional.of(new TargetDefault.LocalTimestamp(mapped)), IdentityIntent.NONE,
                List.of())), List.of());

        String ddl = sql(PAIR.target().ddlPlan(table)).get(0);

        assertEquals("CREATE TABLE \"shop\".\"orders\" (\"created_at\" timestamp(3) without time zone NOT NULL "
                + "DEFAULT LOCALTIMESTAMP(3))", ddl, "TP §7.3: CURRENT_TIMESTAMP(6) is LOCALTIMESTAMP(3) on timestamp(3)");
        assertThrows(IllegalArgumentException.class, () -> new TargetDefault.LocalTimestamp(6),
                "TP §6.4: a microsecond default is not expressible; it arrives at min(n,3)");
    }

    // --- Fingerprints (ADR-0008 §Plans; #123 Testing Decisions) --------------------------------------

    @Test
    void everyInputFieldChangesTheFingerprint() {
        TargetTable base = orders();
        Map<String, TargetTable> variants = new LinkedHashMap<>();
        variants.put("schema", new TargetTable(new TargetTableCoordinate(id("shop2"), id("orders")), base.columns(),
                base.primaryKey()));
        variants.put("table name", new TargetTable(new TargetTableCoordinate(id("shop"), id("orders2")), base.columns(),
                base.primaryKey()));
        variants.put("column name", replace(base, 3, new TargetColumn(id("created"), TIMESTAMP_3, Nullability.NOT_NULL,
                Optional.of(new TargetDefault.LocalTimestamp(3)), IdentityIntent.NONE, List.of())));
        variants.put("column type", replace(base, 2, new TargetColumn(id("total"), TEXT, Nullability.NULLABLE,
                Optional.of(new TargetDefault.Literal(new SqlValue.Decimal(new BigDecimal("0.00")))),
                IdentityIntent.NONE, List.of())));
        variants.put("type modifier", replace(base, 2, new TargetColumn(id("total"),
                new TargetType(TargetTypeName.NUMERIC, List.of(12, 2)), Nullability.NULLABLE,
                Optional.of(new TargetDefault.Literal(new SqlValue.Decimal(new BigDecimal("0.00")))),
                IdentityIntent.NONE, List.of())));
        variants.put("column order", new TargetTable(base.table(),
                List.of(base.columns().get(0), base.columns().get(2), base.columns().get(1), base.columns().get(3)),
                base.primaryKey()));
        variants.put("sequence name", replace(base, 0, new TargetColumn(id("id"), NUMERIC_20_0, Nullability.NOT_NULL,
                Optional.empty(), new IdentityIntent.OwnedSequence(id("orders_seq")), List.of())));
        variants.put("literal value", replace(base, 2, new TargetColumn(id("total"), NUMERIC_10_2, Nullability.NULLABLE,
                Optional.of(new TargetDefault.Literal(new SqlValue.Decimal(new BigDecimal("0.0")))),
                IdentityIntent.NONE, List.of())));
        variants.putAll(toggles());

        assertAllDistinct(base, variants);
    }

    /** Each ADR-0011 element toggled on and off, and its rendered fragment present exactly when it is on. */
    @Test
    void eachAdr0011ElementToggledChangesTheTextAndTheFingerprint() {
        TargetTable off = table(List.of(
                new TargetColumn(id("id"), BIGINT, Nullability.NULLABLE),
                new TargetColumn(id("k"), BIGINT, Nullability.NOT_NULL),
                new TargetColumn(id("status"), TEXT, Nullability.NULLABLE)), List.of());
        record Toggle(String element, TargetTable on, String fragment) {
        }
        List<Toggle> toggles = List.of(
                new Toggle("nullability", replace(off, 0, new TargetColumn(id("id"), BIGINT, Nullability.NOT_NULL)),
                        "\"id\" bigint NOT NULL"),
                new Toggle("default", replace(off, 0, new TargetColumn(id("id"), BIGINT, Nullability.NULLABLE,
                        Optional.of(new TargetDefault.Literal(new SqlValue.Int64(7))), IdentityIntent.NONE, List.of())),
                        "DEFAULT 7"),
                new Toggle("identity", replace(off, 0, new TargetColumn(id("id"), BIGINT, Nullability.NOT_NULL,
                        Optional.empty(), IdentityIntent.IDENTITY_BY_DEFAULT, List.of())),
                        "GENERATED BY DEFAULT AS IDENTITY"),
                new Toggle("primary key", new TargetTable(off.table(), off.columns(), List.of(id("k"))),
                        "PRIMARY KEY (\"k\")"),
                new Toggle("ENUM members", replace(off, 2, new TargetColumn(id("status"), TEXT, Nullability.NULLABLE,
                        Optional.empty(), IdentityIntent.NONE, List.of("a"))),
                        "CHECK (\"status\" IN (E'a'))"));
        for (Toggle toggle : toggles) {
            SqlPlan onPlan = PAIR.target().ddlPlan(toggle.on());
            SqlPlan offPlan = PAIR.target().ddlPlan(off);
            assertTrue(String.join("\n", sql(onPlan)).contains(toggle.fragment()),
                    "ADR-0011 §DDL: " + toggle.element() + " on renders " + toggle.fragment() + ": " + sql(onPlan));
            assertFalse(String.join("\n", sql(offPlan)).contains(toggle.fragment()),
                    "ADR-0011 §DDL: " + toggle.element() + " off renders nothing: " + sql(offPlan));
            assertTrue(!onPlan.fingerprint().equals(offPlan.fingerprint()),
                    "ADR-0008 §Plans: toggling " + toggle.element() + " changes the fingerprint");
        }
        assertAllDistinct(off, Map.of(
                "key order a,b", keyed(List.of(id("id"), id("k"))),
                "key order b,a", keyed(List.of(id("k"), id("id")))));
    }

    /**
     * Pinned from the independent {@code SqlPlan/1} model (length-prefixed UTF-8, big-endian ints, SHA-256) over
     * the three literal statements of {@link #theStatementsArePinnedForARepresentativeTable}, computed outside
     * Java. A change here is a change of DDL text or of the encoding, never noise.
     */
    @Test
    void theRepresentativeFingerprintIsPinnedFromTheIndependentModel() {
        assertEquals("07693e7697ff1d065a707d39a84f8ee7c5bff038a91f25ff065437d0da380b89", PAIR.target().ddlPlan(orders()).fingerprint().sha256Hex(),
                "ADR-0008 §Plans: the DDL plan fingerprint must not depend on the JVM, the machine or the run");
    }

    // --- Hostile identifiers and values (ADR-0008 §Plans; TP §7.1) -----------------------------------

    private static final List<String> HOSTILE = List.of(
            "it's", "back\\slash", "$$dollar$$", "`tick`", "new\nline", "cr\rtab\t", "a\"b", "?", "soh",
            "del", "客户订单", "emoji😀", "x\"; DROP TABLE t; --", "'); DROP TABLE t; --", "a''b", "e\\'");

    @Test
    void hostileIdentifiersNeverChangeStatementStructure() {
        List<String> benign = skeleton(sql(PAIR.target().ddlPlan(named("s", "t", "c", "q"))));
        for (String hostile : HOSTILE) {
            SqlPlan plan = PAIR.target().ddlPlan(named(hostile, hostile + "t", hostile + "c", hostile + "q"));
            assertEquals(benign, skeleton(sql(plan)),
                    "TP §7.1: a hostile name stays inside its quotes and literal: " + hostile);
            plan.statements().forEach(statement -> assertEquals(0, statement.parameters().size(),
                    "ADR-0008 §Plans: parameter count equals placeholder count, which is zero in DDL"));
        }
    }

    @Test
    void anIdentifierOf63BytesIsKeptAndOf64BytesIsRefused() {
        String bytes63 = "订".repeat(21);
        String other63 = "é".repeat(31) + "a";
        String bytes64 = "订".repeat(21) + "a";
        assertEquals(63, bytes63.getBytes(StandardCharsets.UTF_8).length);
        assertEquals(63, other63.getBytes(StandardCharsets.UTF_8).length);

        String ddl = String.join("\n", sql(PAIR.target().ddlPlan(named(bytes63, bytes63, "a".repeat(62), other63))));
        for (String kept : List.of(bytes63, other63, "a".repeat(62) + "e")) {
            assertTrue(ddl.contains("\"" + kept + "\""),
                    "TP §7.1: a 63-byte name is PostgreSQL's limit and is kept exactly: " + kept);
        }
        for (TargetTable table : List.of(named(bytes64, "t", "c", "q"), named("s", bytes64, "c", "q"),
                named("s", "t", bytes64, "q"), named("s", "t", "c", bytes64))) {
            assertThrows(IllegalArgumentException.class, () -> PAIR.target().ddlPlan(table),
                    "TP §7.1: PostgreSQL truncates a 64-byte name, so DDL would create a different object");
        }
    }

    @Test
    void theLiteralRendererKeepsHostileValuesInertAndExact() {
        Map<SqlValue, String> expected = new LinkedHashMap<>();
        expected.put(new SqlValue.Text("it's"), "E'it''s'");
        expected.put(new SqlValue.Text("back\\slash"), "E'back\\\\slash'");
        expected.put(new SqlValue.Text("e\\'"), "E'e\\\\'''");
        expected.put(new SqlValue.Text("$$dollar$$"), "E'$$dollar$$'");
        expected.put(new SqlValue.Text("`tick`\"q\"?"), "E'`tick`\"q\"?'");
        expected.put(new SqlValue.Text("new\nline\r\t"), "E'new\\u000Aline\\u000D\\u0009'");
        expected.put(new SqlValue.Text(""), "E'\\u0001\\u007F\\u0085'");
        expected.put(new SqlValue.Text("客户😀"), "E'客户😀'");
        expected.put(new SqlValue.Text(""), "E''");
        expected.put(new SqlValue.Int64(Long.MIN_VALUE), "-9223372036854775808");
        expected.put(new SqlValue.Decimal(new BigDecimal("-0.50")), "-0.50");
        expected.put(new SqlValue.Decimal(new BigDecimal("1E+3")), "1000");
        expected.put(new SqlValue.Bool(true), "true");
        expected.put(new SqlValue.Bytes(new byte[] {0x00, (byte) 0xFF, 0x27, 0x5C}), "E'\\\\x00ff275c'::bytea");
        for (Map.Entry<SqlValue, String> entry : expected.entrySet()) {
            TargetTable table = table(List.of(new TargetColumn(id("c"), TEXT, Nullability.NULLABLE,
                    Optional.of(new TargetDefault.Literal(entry.getKey())), IdentityIntent.NONE, List.of())), List.of());
            assertEquals("CREATE TABLE \"shop\".\"orders\" (\"c\" text DEFAULT " + entry.getValue() + ")",
                    sql(PAIR.target().ddlPlan(table)).get(0),
                    "ADR-0008 §Plans as amended by #123: the typed literal renderer spells " + entry.getKey());
        }
        List<String> benign = skeleton(sql(PAIR.target().ddlPlan(enumTable("a", "b"))));
        for (String hostile : HOSTILE) {
            assertEquals(benign, skeleton(sql(PAIR.target().ddlPlan(enumTable(hostile, hostile + "2")))),
                    "ADR-0008 §Plans: a hostile ENUM member or default never leaves its literal: " + hostile);
        }
    }

    @Test
    void aTextValuePostgresCannotHoldIsRefusedRatherThanAltered() {
        for (String unstorable : List.of("nul inside", "lone\uD800surrogate", "low\uDC00first")) {
            assertThrows(IllegalArgumentException.class, () -> PAIR.target().ddlPlan(enumTable(unstorable, "b")),
                    "ADR-0008 §Plans: PostgreSQL text holds no U+0000 or lone surrogate, so the renderer refuses it");
        }
    }

    // --- Nothing beyond the minimal writable table (ADR-0011 §DDL) ------------------------------------

    private static final Pattern FORBIDDEN = Pattern.compile(
            "\\b(IF\\s+NOT\\s+EXISTS|OR\\s+REPLACE|DROP|CASCADE|CREATE\\s+SCHEMA|GRANT|INDEX|FOREIGN|REFERENCES"
                    + "|COMMENT|COLLATE|CONSTRAINT|UNIQUE|TRIGGER|TRUNCATE|INSERT|UPDATE|DELETE)\\b",
            Pattern.CASE_INSENSITIVE);

    @Test
    void ddlCarriesNoForbiddenTokenOutsideItsQuotedNamesAndLiterals() {
        List<TargetTable> tables = new ArrayList<>(List.of(orders(), toggles().get("primary key")));
        HOSTILE.forEach(hostile -> tables.add(named(hostile, hostile, hostile + "c", hostile + "q")));
        tables.add(enumTable("DROP TABLE x CASCADE", "CREATE INDEX i ON t (c) COLLATE \"C\""));
        for (TargetTable table : tables) {
            for (String statement : skeleton(sql(PAIR.target().ddlPlan(table)))) {
                assertFalse(FORBIDDEN.matcher(statement).find(),
                        "ADR-0011 §DDL: DDL never reuses, replaces, drops, grants, indexes, references, comments, "
                                + "collates or names a constraint: " + statement);
                assertTrue(statement.startsWith("CREATE TABLE ") || statement.startsWith("CREATE SEQUENCE ")
                                || statement.startsWith("ALTER SEQUENCE "),
                        "ADR-0011 §DDL: only the table and its owned sequence are created: " + statement);
            }
        }
    }

    // --- Inconsistent tables are refused (ADR-0011 §DDL; TP §7.3) ------------------------------------

    @Test
    void anInconsistentTableCannotBeConstructed() {
        TargetColumn plain = new TargetColumn(id("c"), BIGINT, Nullability.NOT_NULL);
        Map<String, Supplier<Object>> inconsistent = new LinkedHashMap<>();
        inconsistent.put("a key column not in the table", () -> table(List.of(plain), List.of(id("missing"))));
        inconsistent.put("a key column twice", () -> table(List.of(plain), List.of(id("c"), id("c"))));
        inconsistent.put("a nullable key column", () -> table(
                List.of(new TargetColumn(id("c"), BIGINT, Nullability.NULLABLE)), List.of(id("c"))));
        inconsistent.put("a column twice", () -> table(List.of(plain, plain), List.of()));
        for (TargetType nonInteger : List.of(NUMERIC_20_0, TEXT, new TargetType(TargetTypeName.REAL, List.of()))) {
            inconsistent.put("identity on " + nonInteger, () -> new TargetColumn(id("c"), nonInteger,
                    Nullability.NOT_NULL, Optional.empty(), IdentityIntent.IDENTITY_BY_DEFAULT, List.of()));
        }
        for (TargetType notNumeric20 : List.of(BIGINT, NUMERIC_10_2, new TargetType(TargetTypeName.NUMERIC, List.of(20, 1)),
                new TargetType(TargetTypeName.NUMERIC, List.of(19, 0)))) {
            inconsistent.put("owned sequence on " + notNumeric20, () -> new TargetColumn(id("c"), notNumeric20,
                    Nullability.NOT_NULL, Optional.empty(), new IdentityIntent.OwnedSequence(id("q")), List.of()));
        }
        inconsistent.put("a nullable identity", () -> new TargetColumn(id("c"), BIGINT, Nullability.NULLABLE,
                Optional.empty(), IdentityIntent.IDENTITY_BY_DEFAULT, List.of()));
        inconsistent.put("an identity with a default", () -> new TargetColumn(id("c"), BIGINT, Nullability.NOT_NULL,
                Optional.of(new TargetDefault.Literal(new SqlValue.Int64(1))), IdentityIntent.IDENTITY_BY_DEFAULT,
                List.of()));
        inconsistent.put("two generated columns", () -> table(List.of(
                new TargetColumn(id("a"), BIGINT, Nullability.NOT_NULL, Optional.empty(),
                        IdentityIntent.IDENTITY_BY_DEFAULT, List.of()),
                new TargetColumn(id("b"), BIGINT, Nullability.NOT_NULL, Optional.empty(),
                        IdentityIntent.IDENTITY_BY_DEFAULT, List.of())), List.of()));
        inconsistent.put("a sequence named like its table", () -> table(List.of(new TargetColumn(id("id"), NUMERIC_20_0,
                Nullability.NOT_NULL, Optional.empty(), new IdentityIntent.OwnedSequence(id("orders")), List.of())),
                List.of()));
        inconsistent.put("LOCALTIMESTAMP on a non-timestamp", () -> new TargetColumn(id("c"), TEXT, Nullability.NULLABLE,
                Optional.of(new TargetDefault.LocalTimestamp(3)), IdentityIntent.NONE, List.of()));
        inconsistent.put("LOCALTIMESTAMP at another precision", () -> new TargetColumn(id("c"), TIMESTAMP_3,
                Nullability.NULLABLE, Optional.of(new TargetDefault.LocalTimestamp(0)), IdentityIntent.NONE, List.of()));
        inconsistent.put("ENUM members on a non-text target", () -> new TargetColumn(id("c"), BIGINT,
                Nullability.NULLABLE, Optional.empty(), IdentityIntent.NONE, List.of("a")));
        inconsistent.put("duplicate ENUM members", () -> new TargetColumn(id("c"), TEXT, Nullability.NULLABLE,
                Optional.empty(), IdentityIntent.NONE, List.of("a", "a")));
        inconsistent.put("a NULL literal default", () -> new TargetDefault.Literal(new SqlValue.Null(SqlValue.Type.TEXT)));

        for (Map.Entry<String, Supplier<Object>> entry : inconsistent.entrySet()) {
            assertThrows(IllegalArgumentException.class, entry.getValue()::get,
                    "ADR-0011 §DDL: a table whose DDL could not be proven equal to it is refused: " + entry.getKey());
        }
        assertThrows(IllegalArgumentException.class, () -> PAIR.target().ddlPlan(table(List.of(new TargetColumn(id("c"),
                        new TargetType(TargetTypeName.VARCHAR, List.of()), Nullability.NULLABLE)), List.of())),
                "TP §6.3: varchar without its length is not an exact type");
    }

    // --- Fixtures -------------------------------------------------------------------------------------

    private static TargetIdentifier id(String name) {
        return new TargetIdentifier(name);
    }

    private static TargetTable table(List<TargetColumn> columns, List<TargetIdentifier> key) {
        return new TargetTable(new TargetTableCoordinate(id("shop"), id("orders")), columns, key);
    }

    /** Owned sequence, ENUM with a literal default, a decimal default, LOCALTIMESTAMP(3), primary key. */
    private static TargetTable orders() {
        return table(List.of(
                new TargetColumn(id("id"), NUMERIC_20_0, Nullability.NOT_NULL, Optional.empty(),
                        new IdentityIntent.OwnedSequence(id("orders_id_seq")), List.of()),
                new TargetColumn(id("status"), TEXT, Nullability.NOT_NULL,
                        Optional.of(new TargetDefault.Literal(new SqlValue.Text("new"))), IdentityIntent.NONE,
                        List.of("new", "paid")),
                new TargetColumn(id("total"), NUMERIC_10_2, Nullability.NULLABLE,
                        Optional.of(new TargetDefault.Literal(new SqlValue.Decimal(new BigDecimal("0.00")))),
                        IdentityIntent.NONE, List.of()),
                new TargetColumn(id("created_at"), TIMESTAMP_3, Nullability.NOT_NULL,
                        Optional.of(new TargetDefault.LocalTimestamp(3)), IdentityIntent.NONE, List.of())),
                List.of(id("id")));
    }

    /** One variant of {@link #orders()} per ADR-0011 element switched off or changed. */
    private static Map<String, TargetTable> toggles() {
        TargetTable base = orders();
        Map<String, TargetTable> variants = new LinkedHashMap<>();
        variants.put("nullability", replace(base, 2, new TargetColumn(id("total"), NUMERIC_10_2, Nullability.NOT_NULL,
                Optional.of(new TargetDefault.Literal(new SqlValue.Decimal(new BigDecimal("0.00")))),
                IdentityIntent.NONE, List.of())));
        variants.put("default removed", replace(base, 2, new TargetColumn(id("total"), NUMERIC_10_2,
                Nullability.NULLABLE)));
        variants.put("default kind", replace(base, 1, new TargetColumn(id("status"), TEXT, Nullability.NOT_NULL,
                Optional.of(new TargetDefault.Literal(new SqlValue.Int64(0))), IdentityIntent.NONE,
                List.of("new", "paid"))));
        variants.put("identity removed", replace(base, 0, new TargetColumn(id("id"), NUMERIC_20_0, Nullability.NOT_NULL)));
        variants.put("primary key", new TargetTable(base.table(), base.columns(), List.of()));
        variants.put("ENUM members removed", replace(base, 1, new TargetColumn(id("status"), TEXT, Nullability.NOT_NULL,
                Optional.of(new TargetDefault.Literal(new SqlValue.Text("new"))), IdentityIntent.NONE, List.of())));
        variants.put("ENUM member order", replace(base, 1, new TargetColumn(id("status"), TEXT, Nullability.NOT_NULL,
                Optional.of(new TargetDefault.Literal(new SqlValue.Text("new"))), IdentityIntent.NONE,
                List.of("paid", "new"))));
        variants.put("ENUM member added", replace(base, 1, new TargetColumn(id("status"), TEXT, Nullability.NOT_NULL,
                Optional.of(new TargetDefault.Literal(new SqlValue.Text("new"))), IdentityIntent.NONE,
                List.of("new", "paid", "void"))));
        variants.put("key order", new TargetTable(base.table(), base.columns(), List.of(id("status"), id("id"))));
        variants.put("key width", new TargetTable(base.table(), base.columns(), List.of(id("id"), id("status"))));
        return variants;
    }

    private static TargetTable keyed(List<TargetIdentifier> key) {
        return table(List.of(
                new TargetColumn(id("id"), BIGINT, Nullability.NOT_NULL),
                new TargetColumn(id("k"), BIGINT, Nullability.NOT_NULL),
                new TargetColumn(id("status"), TEXT, Nullability.NULLABLE)), key);
    }

    /** Every name position filled from the arguments, with an owned sequence, a key and an ENUM CHECK. */
    private static TargetTable named(String schema, String table, String column, String sequence) {
        return new TargetTable(new TargetTableCoordinate(id(schema), id(table)), List.of(
                new TargetColumn(id(column), NUMERIC_20_0, Nullability.NOT_NULL, Optional.empty(),
                        new IdentityIntent.OwnedSequence(id(sequence)), List.of()),
                new TargetColumn(id(column + "e"), TEXT, Nullability.NULLABLE, Optional.empty(), IdentityIntent.NONE,
                        List.of("a"))),
                List.of(id(column)));
    }

    private static TargetTable enumTable(String first, String second) {
        return table(List.of(new TargetColumn(id("c"), TEXT, Nullability.NULLABLE,
                Optional.of(new TargetDefault.Literal(new SqlValue.Text(first))), IdentityIntent.NONE,
                List.of(first, second))), List.of());
    }

    private static TargetTable replace(TargetTable table, int index, TargetColumn column) {
        List<TargetColumn> columns = new ArrayList<>(table.columns());
        columns.set(index, column);
        return new TargetTable(table.table(), columns, table.primaryKey());
    }

    private static List<String> sql(SqlPlan plan) {
        return plan.statements().stream().map(ParameterizedStatement::sql).toList();
    }

    private static void assertAllDistinct(TargetTable base, Map<String, TargetTable> variants) {
        Map<PlanFingerprint, String> seen = new HashMap<>();
        seen.put(PAIR.target().ddlPlan(base).fingerprint(), "base");
        for (Map.Entry<String, TargetTable> variant : variants.entrySet()) {
            String previous = seen.put(PAIR.target().ddlPlan(variant.getValue()).fingerprint(), variant.getKey());
            assertEquals(null, previous, "ADR-0008 §Plans: changing only the " + variant.getKey()
                    + " must change the fingerprint, but it equals " + previous);
        }
    }

    /**
     * The statement with every double-quoted identifier replaced by {@code "_"} and every escape-string literal
     * by {@code E'_'}: what remains is the structure a hostile name or value must not change.
     */
    private static List<String> skeleton(List<String> statements) {
        return statements.stream().map(TargetDialectContractTest::skeleton).toList();
    }

    private static String skeleton(String sql) {
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < sql.length(); i++) {
            char c = sql.charAt(i);
            if (c == '"') {
                i++;
                while (!(sql.charAt(i) == '"' && (i + 1 == sql.length() || sql.charAt(i + 1) != '"'))) {
                    i += sql.charAt(i) == '"' ? 2 : 1;
                }
                out.append("\"_\"");
            } else if (c == '\'') {
                i++;
                while (!(sql.charAt(i) == '\'' && (i + 1 == sql.length() || sql.charAt(i + 1) != '\''))) {
                    i += sql.charAt(i) == '\'' || sql.charAt(i) == '\\' ? 2 : 1;
                }
                out.append("'_'");
            } else {
                out.append(c);
            }
        }
        return out.toString();
    }
}
