import type { Preflight, PreflightConclusion, TableWriteContract } from './tableMigrationUnit';

/**
 * 逐表配置 — what the wizard's third stage works on, before any 迁移运行 exists.
 *
 * `CONTEXT.md` defines a 迁移草稿 as an unapproved working set of wizard selections **and
 * per-table configuration**, so this is draft-scoped rather than run-scoped: a
 * 表迁移单元 belongs to a 迁移运行 and there is none yet. What the two share is the
 * 表写入契约 and the 预检, which is why both are reused from `tableMigrationUnit.ts`
 * rather than redefined here.
 *
 * ADR-0011 governs everything below. The 表写入契约 is assembled by the platform from
 * normalized source metadata, the database pair's mapping decisions, structured 映射规则
 * and exact 预检 findings; DDL is **one complete read-only rendering of that contract**,
 * never a second editable configuration. That is why nothing in this module describes a
 * DDL edit, and why a mapping change is expressed as a 映射规则 rather than as text.
 */

/**
 * The bounded action a 映射规则 may take.
 *
 * `CONTEXT.md`: a rule 「names one source coordinate, one bounded action, its target
 * value」 and 「never contains arbitrary SQL or regular expressions in v1」. The union is
 * therefore closed, and adding a member is a domain decision rather than a UI convenience.
 */
export type MappingRuleAction = 'TARGET_TYPE' | 'NULLABILITY' | 'IDENTITY' | 'DEFAULT_VALUE';

/** 「whether DBX or the user produced it; user rules override automatic rules」. */
export type MappingRuleOrigin = 'PLATFORM' | 'USER';

/** One structured, reviewable exception to DBX's automatic mapping. */
export interface MappingRule {
  /** Stable within one table: `<sourceColumn>:<action>`. */
  readonly id: string;
  /** The one source coordinate the rule names. */
  readonly sourceColumn: string;
  readonly action: MappingRuleAction;
  /**
   * The rule's target value, as the target dialect writes it — `numeric(20,0)`,
   * `NOT NULL`, `GENERATED BY DEFAULT AS IDENTITY`. A technical literal, never prose.
   */
  readonly targetValue: string;
  readonly origin: MappingRuleOrigin;
}

/**
 * Why automatic mapping did not settle this coordinate.
 *
 * A closed set of codes rather than server prose: the wording belongs in `src/messages`
 * with the rest of the interface's copy, and a code keeps the mock, the contract and the
 * copy from drifting apart. Every member is a case ADR-0011 names explicitly.
 */
export type MappingExceptionReason =
  /** MySQL `enum` has no v1 target type; the value domain has to be carried by a string. */
  | 'ENUM_VALUE_DOMAIN'
  /** An unsigned integer whose range does not fit the signed target type. */
  | 'UNSIGNED_INTEGER_RANGE'
  /** `numeric(20,0)` auto-increment: identity, or an owned explicit sequence (ADR-0011). */
  | 'AUTO_INCREMENT_IDENTITY'
  /** A zero-date default: outside the whitelist, and only relaxable per column, by decision. */
  | 'ZERO_DATE_DEFAULT';

/** One bounded choice offered for an exception. Never free text. */
export interface MappingRuleOption {
  /** What the rule would be set to. Rendered as the technical literal it is. */
  readonly targetValue: string;
  /** Stable code for the consequence of choosing it; wording lives in `src/messages`. */
  readonly consequence: MappingRuleConsequence;
}

export type MappingRuleConsequence =
  | 'PRESERVES_VALUE_DOMAIN'
  | 'FIXED_WIDTH_MAY_TRUNCATE'
  | 'WIDER_TARGET_TYPE'
  | 'EXACT_NUMERIC_TARGET'
  | 'PLATFORM_OWNED_IDENTITY'
  | 'OWNED_EXPLICIT_SEQUENCE'
  | 'REJECTS_ZERO_DATE'
  | 'APPROVED_ZERO_DATE_RELAXATION';

/**
 * One structured mapping exception, as the workspace lists it.
 *
 * Story 37: the exceptions are collected in one place so the operator never has to check
 * every field by hand. Story 36: automatic mapping is the default, so most exceptions
 * arrive with a `PLATFORM` rule already in force and need only review.
 */
export interface MappingException {
  readonly sourceColumn: string;
  /** The source type, character for character as MySQL reports it. */
  readonly sourceType: string;
  readonly action: MappingRuleAction;
  readonly reason: MappingExceptionReason;
  readonly options: readonly MappingRuleOption[];
  /**
   * The rule in force, or `null` when DBX will not choose on the operator's behalf.
   *
   * A null rule is the honest case ADR-0011 creates: the per-column zero-date relaxation
   * is *approved*, so the platform may not assume it. Until it is decided the table has no
   * complete 表写入契约, and therefore no DDL — because DDL is a complete rendering of the
   * contract and half of one would be a lie.
   */
  readonly rule: MappingRule | null;
}

/** How a source object relates to the v1 writable-table boundary (ADR-0011). */
export type TableObjectKind =
  'COLUMN' | 'PRIMARY_KEY' | 'UNIQUE_CONSTRAINT' | 'INDEX' | 'FOREIGN_KEY';

/**
 * One node of the object tree.
 *
 * The tree earns its pane by saying which source objects the migration actually carries:
 * ADR-0011 puts unique constraints other than the primary key, ordinary indexes, foreign
 * keys, comments and collation **outside** the live v1 contract, preserved as 补建 SQL and
 * not executed during migration. A tree that showed them without saying so would imply a
 * structural migration DBX does not perform.
 */
export interface TableObjectNode {
  readonly id: string;
  readonly kind: TableObjectKind;
  readonly name: string;
  /** Source-side detail: a column's type, an index's columns. A technical literal. */
  readonly detail: string;
  /** False when the object is preserved as 补建 SQL rather than migrated. */
  readonly inWritableContract: boolean;
  /** Whether this coordinate carries a structured mapping exception. */
  readonly hasMappingException: boolean;
}

/**
 * The per-table summary the wizard needs before it opens any single table.
 *
 * Deliberately small: the 迁移范围 can hold 1200 tables, so this is what the object tree
 * and the stage's gate read, and the full workspace below is fetched one table at a time.
 */
export interface DraftTableConfiguration {
  readonly sourceTable: string;
  readonly targetTable: string;
  readonly preflightConclusion: PreflightConclusion;
  readonly blockingFindingCount: number;
  readonly largeRecordTable: boolean;
  readonly mappingExceptionCount: number;
  /** Exceptions DBX will not decide on the operator's behalf, still undecided. */
  readonly undecidedMappingExceptionCount: number;
  /**
   * The version of the table's 表写入契约, or `null` when there is none yet because an
   * exception is still undecided. The stage's gate reads exactly this.
   */
  readonly contractVersion: number | null;
}

/**
 * Everything the single-table workspace shows for one table.
 *
 * One aggregate rather than four requests, because the three panes are a single judgement:
 * story 38 asks to see the object tree, both DDLs and the findings 「在一个屏幕内」, and
 * fetching them separately would let the DDL disagree with the exception list that
 * produced it.
 */
export interface DraftTableWorkspace {
  readonly sourceTable: string;
  readonly targetTable: string;
  readonly sourceDatabase: string;
  readonly targetSchema: string;
  /** The source table as MySQL 8.0 reports it. Read-only, like everything here. */
  readonly sourceDdl: string;
  readonly objectTree: readonly TableObjectNode[];
  readonly mappingExceptions: readonly MappingException[];
  readonly preflight: Preflight;
  /** Null while an exception is undecided: an incomplete contract is not rendered. */
  readonly tableWriteContract: TableWriteContract | null;
}

/**
 * Recording one user 映射规则.
 *
 * The request names a coordinate and a bounded action — never SQL. Recording it replaces
 * any rule already in force for that coordinate, regenerates the 表写入契约 and reruns the
 * affected 预检, which is ADR-0011's 「A mapping change creates a new draft and reruns
 * every affected preflight」.
 */
export interface RecordMappingRuleRequest {
  readonly sourceTable: string;
  readonly sourceColumn: string;
  readonly action: MappingRuleAction;
  readonly targetValue: string;
}
