import { describe, expect, it } from 'vitest';
import { tokeniseSql } from './sqlHighlight';

const ddl = `CREATE TABLE "orders_migrated"."order_item" (
  "id" numeric(20,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "status_code" text NOT NULL DEFAULT 'pending',
  CONSTRAINT "pk_order_item" PRIMARY KEY ("id")
);`;

describe('the DBX SQL palette', () => {
  it('reproduces the DDL character for character', () => {
    // ADR-0011 preserves identifiers character-for-character. A highlighter that dropped
    // or normalised one would be showing DDL that is not the DDL — which on a read-only
    // rendering of the 表写入契约 is the only failure that really matters.
    expect(
      tokeniseSql(ddl)
        .map((token) => token.text)
        .join(''),
    ).toBe(ddl);
    expect(
      tokeniseSql('')
        .map((token) => token.text)
        .join(''),
    ).toBe('');
  });

  it('keeps quoted identifiers whole, backticks and double quotes alike', () => {
    const identifiers = tokeniseSql(ddl)
      .filter((token) => token.kind === 'identifier')
      .map((token) => token.text);
    expect(identifiers).toContain('"order_item"');
    expect(identifiers).toContain('"pk_order_item"');

    const mysql = tokeniseSql('CREATE TABLE `orders`.`order_item` (`id` bigint NOT NULL)');
    expect(mysql.filter((token) => token.kind === 'identifier').map((token) => token.text)).toEqual(
      ['`orders`', '`order_item`', '`id`'],
    );
  });

  it('separates keywords, types and literals', () => {
    const tokens = tokeniseSql(ddl);
    const kindOf = (text: string) => tokens.find((token) => token.text === text)?.kind;
    expect(kindOf('CREATE')).toBe('keyword');
    expect(kindOf('IDENTITY')).toBe('keyword');
    expect(kindOf('numeric')).toBe('type');
    expect(kindOf('text')).toBe('type');
    expect(kindOf("'pending'")).toBe('string');
    expect(kindOf('20')).toBe('number');
  });

  it('does not mistake an identifier that contains a keyword for a keyword', () => {
    // `order_key` is a column, not a `KEY` clause; colouring it as one would misread the
    // structure the DDL is stating.
    const tokens = tokeniseSql('  "order_key" text NOT NULL');
    expect(tokens.find((token) => token.text === '"order_key"')?.kind).toBe('identifier');
  });
});
