package com.dbx.dialect.api;

/** What a mapping adds to the table write contract (ADR-0011; TP §7.3). Owned by slice 3. */
public enum ContractEffect {
    /** {@code ENUM} → {@code text}: the target column carries a {@code CHECK} over the declared members (TP §6.3). */
    ENUM_CHECK_CONSTRAINT,
    /**
     * An {@code AUTO_INCREMENT} column with an integer target becomes {@code GENERATED BY DEFAULT AS
     * IDENTITY} (TP §7.3; ADR-0011 §DDL).
     */
    IDENTITY_GENERATED_BY_DEFAULT,
    /**
     * An {@code AUTO_INCREMENT BIGINT UNSIGNED} lands in {@code numeric(20,0)}, which cannot be an identity
     * column, so the target gets an explicit owned {@code bigint} sequence as its default (TP §7.3;
     * ADR-0011 §DDL). The sequence ceiling is narrower than the source's (ADR-0029 序列上限收窄).
     */
    OWNED_SEQUENCE_FOR_IDENTITY,
    /**
     * The original MySQL type is {@code DATETIME}. Connect carries {@code DATETIME} and {@code TIMESTAMP}
     * as the same Timestamp, so after conversion only this record tells them apart (TP §6.4).
     */
    ORIGINAL_SOURCE_TYPE_DATETIME,
    /** The original MySQL type is {@code TIMESTAMP}; see {@link #ORIGINAL_SOURCE_TYPE_DATETIME} (TP §6.4). */
    ORIGINAL_SOURCE_TYPE_TIMESTAMP,
    /**
     * A source {@code NOT NULL} column under the approved zero-date switch: the target drops {@code NOT NULL}
     * for this column only if the {@link RequiredPreflight#ZERO_DATE_ROWS_COUNTED} scan observed a zero date,
     * and keeps it otherwise (TP §7.3; ADR-0011 §DDL; ADR-0029 非空约束按列放宽).
     */
    NOT_NULL_RELAXED_IF_ZERO_DATES_OBSERVED
}
