package com.dbx.dialect.api;

/**
 * How a target column generates values for a source {@code AUTO_INCREMENT} (ADR-0011 §DDL; TP §7.3).
 * Closed: no identity, {@code GENERATED BY DEFAULT AS IDENTITY} on an integer target, or an owned
 * {@code bigint} sequence for {@code numeric(20,0)}.
 */
public sealed interface IdentityIntent {

    None NONE = new None();

    IdentityByDefault IDENTITY_BY_DEFAULT = new IdentityByDefault();

    record None() implements IdentityIntent {
    }

    /** {@code GENERATED BY DEFAULT AS IDENTITY}: only on {@code smallint}, {@code integer} or {@code bigint}. */
    record IdentityByDefault() implements IdentityIntent {
    }

    /**
     * An explicit {@code bigint} sequence owned by a {@code numeric(20,0)} column. The name is approved and
     * frozen by {@code contract} (obligation 9, #123); the dialect never invents it. The sequence lives in the
     * table's schema, which {@code ALTER SEQUENCE … OWNED BY} requires.
     */
    record OwnedSequence(TargetIdentifier sequence) implements IdentityIntent {

        public OwnedSequence {
            Checks.present(sequence, "sequence");
        }
    }
}
