package com.dbx.dialect.api;

import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

/**
 * A target column as the contract states it and as the catalog reads it back (ADR-0011 §DDL; TP §7.3).
 * Nullability is already resolved: the approved zero-date relaxation arrives as {@code NULLABLE}.
 * {@code enumMembers} is empty unless the column carries an {@code ENUM} {@code CHECK} (TP §6.3). Owned by
 * slices 7 and 8.
 */
public record TargetColumn(
        TargetIdentifier name,
        TargetType type,
        Nullability nullability,
        Optional<TargetDefault> defaultValue,
        IdentityIntent identity,
        List<String> enumMembers) {

    private static final Set<TargetTypeName> INTEGER_TYPES =
            Set.of(TargetTypeName.SMALLINT, TargetTypeName.INTEGER, TargetTypeName.BIGINT);
    private static final Set<TargetTypeName> STRING_TYPES =
            Set.of(TargetTypeName.CHAR, TargetTypeName.VARCHAR, TargetTypeName.TEXT);
    private static final Set<TargetTypeName> TIMESTAMP_TYPES =
            Set.of(TargetTypeName.TIMESTAMP, TargetTypeName.TIMESTAMPTZ);
    private static final TargetType NUMERIC_20_0 = new TargetType(TargetTypeName.NUMERIC, List.of(20, 0));

    public TargetColumn {
        Checks.present(name, "name");
        Checks.present(type, "type");
        Checks.present(nullability, "nullability");
        Checks.present(defaultValue, "defaultValue");
        Checks.present(identity, "identity");
        enumMembers = Checks.list(enumMembers, "enumMembers");
        String column = "column " + name.quoted() + ": ";
        switch (identity) {
            case IdentityIntent.None none -> {
            }
            case IdentityIntent.IdentityByDefault byDefault -> {
                if (!INTEGER_TYPES.contains(type.name())) {
                    throw new IllegalArgumentException(column + "TP §7.3: GENERATED BY DEFAULT AS IDENTITY is for "
                            + "integer targets only, not " + type);
                }
            }
            case IdentityIntent.OwnedSequence owned -> {
                if (!type.equals(NUMERIC_20_0)) {
                    throw new IllegalArgumentException(column + "TP §7.3: an owned sequence is only for an "
                            + "auto-increment BIGINT UNSIGNED mapped to numeric(20,0), not " + type);
                }
            }
        }
        if (!(identity instanceof IdentityIntent.None)) {
            if (nullability != Nullability.NOT_NULL) {
                throw new IllegalArgumentException(column + "ADR-0011 §DDL: PostgreSQL makes a generated column "
                        + "NOT NULL, so a nullable one could never pass structural proof");
            }
            if (defaultValue.isPresent()) {
                throw new IllegalArgumentException(column + "TP §7.3: a generated column takes its values from "
                        + "its identity or sequence and cannot also carry a default");
            }
        }
        if (defaultValue.orElse(null) instanceof TargetDefault.LocalTimestamp timestamp
                && !(TIMESTAMP_TYPES.contains(type.name()) && type.modifiers().equals(List.of(timestamp.precision())))) {
            throw new IllegalArgumentException(column + "TP §7.3: LOCALTIMESTAMP(n) is rendered at the column's "
                    + "mapped timestamp precision, so LOCALTIMESTAMP(" + timestamp.precision() + ") does not fit " + type);
        }
        if (!enumMembers.isEmpty()) {
            if (!STRING_TYPES.contains(type.name())) {
                throw new IllegalArgumentException(column + "TP §6.3: an ENUM CHECK belongs on a text target, not "
                        + type);
            }
            if (new HashSet<>(enumMembers).size() != enumMembers.size()) {
                throw new IllegalArgumentException(column + "TP §6.3: ENUM members are distinct: " + enumMembers);
            }
        }
    }

    /** A plain column: no default, no identity, no {@code ENUM} members. */
    public TargetColumn(TargetIdentifier name, TargetType type, Nullability nullability) {
        this(name, type, nullability, Optional.empty(), IdentityIntent.NONE, List.of());
    }
}
