package com.dbx.dialect.postgres;

import com.dbx.dialect.api.EvidencePolicy;
import com.dbx.dialect.api.IdentityIntent;
import com.dbx.dialect.api.Nullability;
import com.dbx.dialect.api.OperationKind;
import com.dbx.dialect.api.ParameterizedStatement;
import com.dbx.dialect.api.RequiredPrivilege;
import com.dbx.dialect.api.ResultSchema;
import com.dbx.dialect.api.SqlPlan;
import com.dbx.dialect.api.SqlValue;
import com.dbx.dialect.api.TargetColumn;
import com.dbx.dialect.api.TargetDefault;
import com.dbx.dialect.api.TargetIdentifier;
import com.dbx.dialect.api.TargetTable;
import com.dbx.dialect.api.TargetType;
import com.dbx.dialect.api.TimeoutClass;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * {@code target.ddlPlan}: ADR-0011's minimal writable table and nothing more (obligation 24; TP §7.3).
 * Constraints are unnamed, so PostgreSQL picks names that cannot collide with a relation in the schema.
 * Nothing here reuses or replaces an existing object: a first run meeting one fails.
 */
final class PostgresDdl {

    /** PostgreSQL silently truncates a longer identifier, which would change the object DDL creates (TP §7.1). */
    private static final int MAX_IDENTIFIER_BYTES = 63;

    private PostgresDdl() {
    }

    static SqlPlan plan(TargetTable table) {
        String relation = qualified(table.table().schema(), table.table().name());
        List<String> statements = new ArrayList<>();
        IdentityIntent.OwnedSequence owned = table.columns().stream()
                .map(TargetColumn::identity)
                .filter(IdentityIntent.OwnedSequence.class::isInstance)
                .map(IdentityIntent.OwnedSequence.class::cast)
                .findFirst()
                .orElse(null);
        String sequence = owned == null ? null : qualified(table.table().schema(), owned.sequence());
        if (sequence != null) {
            statements.add("CREATE SEQUENCE " + sequence + " AS bigint");
        }
        List<String> elements = new ArrayList<>();
        for (TargetColumn column : table.columns()) {
            elements.add(column(column, sequence));
        }
        if (!table.primaryKey().isEmpty()) {
            elements.add("PRIMARY KEY (" + table.primaryKey().stream().map(PostgresDdl::quoted)
                    .collect(Collectors.joining(", ")) + ")");
        }
        statements.add("CREATE TABLE " + relation + " (" + String.join(", ", elements) + ")");
        if (sequence != null) {
            TargetIdentifier column = table.columns().stream().filter(c -> c.identity().equals(owned)).findFirst()
                    .orElseThrow().name();
            statements.add("ALTER SEQUENCE " + sequence + " OWNED BY " + relation + "." + quoted(column));
        }
        return new SqlPlan(
                OperationKind.TARGET_DDL,
                statements.stream().map(sql -> new ParameterizedStatement(sql, List.of())).toList(),
                ResultSchema.NONE,
                TimeoutClass.DDL,
                Set.of(RequiredPrivilege.TARGET_CREATE_IN_SCHEMA),
                EvidencePolicy.STATEMENT_ONLY);
    }

    private static String column(TargetColumn column, String ownedSequence) {
        StringBuilder sql = new StringBuilder(quoted(column.name())).append(' ').append(type(column.type()));
        if (column.nullability() == Nullability.NOT_NULL) {
            sql.append(" NOT NULL");
        }
        switch (column.identity()) {
            case IdentityIntent.None none -> {
            }
            case IdentityIntent.IdentityByDefault byDefault -> sql.append(" GENERATED BY DEFAULT AS IDENTITY");
            case IdentityIntent.OwnedSequence owned -> sql.append(" DEFAULT nextval(")
                    .append(PostgresLiteral.render(new SqlValue.Text(ownedSequence))).append("::regclass)");
        }
        column.defaultValue().ifPresent(value -> sql.append(" DEFAULT ").append(switch (value) {
            case TargetDefault.Literal literal -> PostgresLiteral.render(literal.value());
            case TargetDefault.LocalTimestamp timestamp -> "LOCALTIMESTAMP(" + timestamp.precision() + ")";
        }));
        if (!column.enumMembers().isEmpty()) {
            sql.append(" CHECK (").append(quoted(column.name())).append(" IN (")
                    .append(column.enumMembers().stream().map(member -> PostgresLiteral.render(new SqlValue.Text(member)))
                            .collect(Collectors.joining(", ")))
                    .append("))");
        }
        return sql.toString();
    }

    /** TP §6.2–6.4's target types, spelled as TP writes them; a modifier count the type cannot take is refused. */
    private static String type(TargetType type) {
        return switch (type.name()) {
            case SMALLINT -> bare(type, "smallint");
            case INTEGER -> bare(type, "integer");
            case BIGINT -> bare(type, "bigint");
            case REAL -> bare(type, "real");
            case DOUBLE_PRECISION -> bare(type, "double precision");
            case BOOLEAN -> bare(type, "boolean");
            case TEXT -> bare(type, "text");
            case BYTEA -> bare(type, "bytea");
            case JSON -> bare(type, "json");
            case JSONB -> bare(type, "jsonb");
            case DATE -> bare(type, "date");
            case NUMERIC -> "numeric(" + modifiers(type, 2) + ")";
            case CHAR -> "char(" + modifiers(type, 1) + ")";
            case VARCHAR -> "varchar(" + modifiers(type, 1) + ")";
            case TIME -> "time(" + modifiers(type, 1) + ") without time zone";
            case TIMESTAMP -> "timestamp(" + modifiers(type, 1) + ") without time zone";
            case TIMESTAMPTZ -> "timestamptz(" + modifiers(type, 1) + ")";
        };
    }

    private static String bare(TargetType type, String name) {
        modifiers(type, 0);
        return name;
    }

    private static String modifiers(TargetType type, int count) {
        if (type.modifiers().size() != count) {
            throw new IllegalArgumentException("TP §6.2–6.4: " + type.name() + " takes " + count
                    + " modifiers, not " + type.modifiers());
        }
        return type.modifiers().stream().map(String::valueOf).collect(Collectors.joining(","));
    }

    static String qualified(TargetIdentifier schema, TargetIdentifier name) {
        return quoted(schema) + "." + quoted(name);
    }

    static String quoted(TargetIdentifier identifier) {
        int bytes = identifier.name().getBytes(StandardCharsets.UTF_8).length;
        if (bytes > MAX_IDENTIFIER_BYTES) {
            throw new IllegalArgumentException("TP §7.1: PostgreSQL truncates identifiers beyond 63 bytes, so "
                    + identifier.quoted() + " (" + bytes + " bytes) would create a different object");
        }
        return identifier.quoted();
    }
}
