package com.dbx.dialect.postgres;

import com.dbx.dialect.api.EvidencePolicy;
import com.dbx.dialect.api.IdentityIntent;
import com.dbx.dialect.api.Nullability;
import com.dbx.dialect.api.OperationKind;
import com.dbx.dialect.api.ParameterizedStatement;
import com.dbx.dialect.api.RequiredPrivilege;
import com.dbx.dialect.api.ResultSchema;
import com.dbx.dialect.api.SqlPlan;
import com.dbx.dialect.api.TargetColumn;
import com.dbx.dialect.api.TargetDefault;
import com.dbx.dialect.api.TargetIdentifier;
import com.dbx.dialect.api.TargetTable;
import com.dbx.dialect.api.TargetType;
import com.dbx.dialect.api.TimeoutClass;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * {@code target.ddlPlan}: ADR-0011's minimal writable table and nothing more (obligation 24; TP §7.3).
 * Constraints are unnamed, so PostgreSQL picks names that cannot collide with a relation in the schema.
 * Nothing here reuses or replaces an existing object: a first run meeting one fails.
 */
final class PostgresDdl {

    private PostgresDdl() {
    }

    static SqlPlan plan(TargetTable table) {
        String relation = PostgresIdentifier.qualified(table.table());
        Optional<TargetColumn> sequenceOwner = table.columns().stream()
                .filter(column -> column.identity() instanceof IdentityIntent.OwnedSequence)
                .findFirst();
        Optional<String> sequence = sequenceOwner.map(column -> PostgresIdentifier.qualified(table.table().schema(),
                ((IdentityIntent.OwnedSequence) column.identity()).sequence()));
        List<String> statements = new ArrayList<>();
        sequence.ifPresent(name -> statements.add("CREATE SEQUENCE " + name + " AS bigint"));
        List<String> elements = new ArrayList<>();
        for (TargetColumn column : table.columns()) {
            elements.add(column(column, sequence));
        }
        if (!table.primaryKey().isEmpty()) {
            elements.add("PRIMARY KEY (" + table.primaryKey().stream().map(PostgresIdentifier::quoted)
                    .collect(Collectors.joining(", ")) + ")");
        }
        statements.add("CREATE TABLE " + relation + " (" + String.join(", ", elements) + ")");
        sequenceOwner.ifPresent(owner -> statements.add("ALTER SEQUENCE " + sequence.orElseThrow() + " OWNED BY "
                + relation + "." + PostgresIdentifier.quoted(owner.name())));
        return new SqlPlan(
                OperationKind.TARGET_DDL,
                statements.stream().map(sql -> new ParameterizedStatement(sql, List.of())).toList(),
                ResultSchema.NONE,
                TimeoutClass.DDL,
                Set.of(RequiredPrivilege.TARGET_CREATE_IN_SCHEMA),
                EvidencePolicy.STATEMENT_ONLY);
    }

    /** {@code ownedSequence} is the qualified sequence of the table's {@code OwnedSequence} column, if it has one. */
    private static String column(TargetColumn column, Optional<String> ownedSequence) {
        StringBuilder sql = new StringBuilder(PostgresIdentifier.quoted(column.name())).append(' ')
                .append(type(column.type()));
        if (column.nullability() == Nullability.NOT_NULL) {
            sql.append(" NOT NULL");
        }
        switch (column.identity()) {
            case IdentityIntent.None none -> {
            }
            case IdentityIntent.IdentityByDefault byDefault -> sql.append(" GENERATED BY DEFAULT AS IDENTITY");
            case IdentityIntent.OwnedSequence owned -> sql.append(" DEFAULT nextval(")
                    .append(PostgresLiteral.text(ownedSequence.orElseThrow())).append("::regclass)");
        }
        column.defaultValue().ifPresent(value -> sql.append(" DEFAULT ").append(switch (value) {
            case TargetDefault.Literal literal -> PostgresLiteral.render(literal.value());
            case TargetDefault.LocalTimestamp timestamp -> "LOCALTIMESTAMP(" + timestamp.precision() + ")";
        }));
        if (!column.enumMembers().isEmpty()) {
            sql.append(" CHECK (").append(PostgresIdentifier.quoted(column.name())).append(" IN (")
                    .append(column.enumMembers().stream().map(PostgresLiteral::text)
                            .collect(Collectors.joining(", ")))
                    .append("))");
        }
        return sql.toString();
    }

    /** TP §6.2–6.4's target types, spelled as TP writes them; a modifier count the type cannot take is refused. */
    private static String type(TargetType type) {
        return switch (type.name()) {
            case SMALLINT -> withoutModifiers(type, "smallint");
            case INTEGER -> withoutModifiers(type, "integer");
            case BIGINT -> withoutModifiers(type, "bigint");
            case REAL -> withoutModifiers(type, "real");
            case DOUBLE_PRECISION -> withoutModifiers(type, "double precision");
            case BOOLEAN -> withoutModifiers(type, "boolean");
            case TEXT -> withoutModifiers(type, "text");
            case BYTEA -> withoutModifiers(type, "bytea");
            case JSON -> withoutModifiers(type, "json");
            case JSONB -> withoutModifiers(type, "jsonb");
            case DATE -> withoutModifiers(type, "date");
            case NUMERIC -> "numeric(" + modifiers(type, 2) + ")";
            case CHAR -> "char(" + modifiers(type, 1) + ")";
            case VARCHAR -> "varchar(" + modifiers(type, 1) + ")";
            case TIME -> "time(" + modifiers(type, 1) + ") without time zone";
            case TIMESTAMP -> "timestamp(" + modifiers(type, 1) + ") without time zone";
            case TIMESTAMPTZ -> "timestamptz(" + modifiers(type, 1) + ")";
        };
    }

    /** {@code name}, after refusing a type that carries modifiers. */
    private static String withoutModifiers(TargetType type, String name) {
        modifiers(type, 0);
        return name;
    }

    private static String modifiers(TargetType type, int count) {
        if (type.modifiers().size() != count) {
            throw new IllegalArgumentException("TP §6.2–6.4: " + type.name() + " takes " + count
                    + " modifiers, not " + type.modifiers());
        }
        return type.modifiers().stream().map(String::valueOf).collect(Collectors.joining(","));
    }
}
