#!/usr/bin/env bash
# S9: reference throughput band (ticket #63, map #1; feeds ADR-0019).
#
# Two measurements on the bulk dataset from e2e/bulk/seed-bulk.sh:
#   single      one table per shape, run alone: one Source task, one Sink task, nothing else
#               on the worker. Yields single-stream throughput, which feeds 窗口下限
#               (minimum window).
#   concurrent  every b_* table at once, one box per table. All of them fit ADR-0002's default
#               admission budgets (see FINDINGS), so rolling admission would start them all
#               immediately. Yields aggregate throughput, which feeds 预估耗时 (duration estimate).
#
# Throughput is reported in the estimator's own unit: ADR-0002 "planned transfer bytes"
# = 1.5 * max(DATA_LENGTH, exact rows * AVG_ROW_LENGTH). The estimator divides those bytes
# by the band, so a band in any other unit would be off by the 1.5x factor and the
# DATA_LENGTH vs payload gap. DATA_LENGTH/s and rows/s are recorded alongside.
#
# The clock starts before the first connector PUT and stops when the target table holds every
# source row (pg_stat n_tup_ins, confirmed with COUNT(*)). That is end-to-end time, the way
# a DBA experiences it, not source read speed.
#
#   ./e2e/bulk/seed-bulk.sh && ./e2e/run-all.sh s9     # both phases
#   PHASES=single ./e2e/run-all.sh s9                   # one phase only
#
# Connector settings follow docs/technical-plan.md §7.4 and ADR-0003. Anything that doc
# leaves unset stays at the connector default and is listed in FINDINGS.
#
# Must stay runnable on macOS's stock bash 3.2: per-table values live in kv_* variables,
# not associative arrays.

source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
init_scenario s9 "reference throughput band"

PHASES="${PHASES:-single concurrent}"
SINGLE_TABLES="${SINGLE_TABLES:-b_narrow_1 b_wide_1 b_lob_1}"
SAMPLE_S="${SAMPLE_S:-1}"
PHASE_TIMEOUT_S="${PHASE_TIMEOUT_S:-5400}"
STALL_S="${STALL_S:-300}"     # abort a phase after this long with no topic or target progress
ORDINARY_POLL_RECORDS=500     # Kafka's own default; ADR-0003 keeps poll=1 for large-record tables only
# Without cursor fetch, Connector/J buffers a Source query's whole result set in the Connect heap:
# the first run of this scenario OOMed the 4 GiB worker with eight concurrent boxes.
# CURSOR_FETCH=0 reproduces the buffered behavior. Fetch size follows each Source's batch.max.rows.
CURSOR_FETCH="${CURSOR_FETCH:-1}"
# The JDBC Source also reads ahead into its own buffer (max.buffer.size; its default derives from
# batch.max.rows, which defaults to 1000 in 10.9.6). With 1.5 MiB rows that buffer alone OOMed a
# fresh 4 GiB worker running the large-record table by itself, so large-record Sources are
# bounded here the way ADR-0003 bounds their Sinks. Lab settings, not a plan decision.
ORDINARY_BATCH_MAX_ROWS=1000                          # the connector default, stated explicitly
LOB_BATCH_MAX_ROWS="${LOB_BATCH_MAX_ROWS:-1}"
LOB_MAX_BUFFER="${LOB_MAX_BUFFER:-4}"
# ADR-0003's size overrides (128 MiB producer buffer, 25 MiB request and partition fetch) on every
# connector left eight concurrent boxes OOMing the 4 GiB Connect heap. ORDINARY_OVERRIDES=0 keeps
# them on the large-record table only and gives ordinary connectors the client defaults. That is
# a lab variant for a provisional band, not a plan decision.
ORDINARY_OVERRIDES="${ORDINARY_OVERRIDES:-1}"
mysql_url() {  # <fetch size>
  local u="jdbc:mysql://mysql:3306/dbx_src?useSSL=false&allowPublicKeyRetrieval=true"
  [ "$CURSOR_FETCH" = 1 ] && u="$u&useCursorFetch=true&defaultFetchSize=$1"
  echo "$u"
}

# Sub-second clock: EPOCHREALTIME on bash 5, perl (shipped with macOS) otherwise
now() {
  if [ -n "${EPOCHREALTIME:-}" ]; then echo "${EPOCHREALTIME/,/.}"
  else perl -MTime::HiRes=time -e 'printf "%.3f\n", time'; fi
}
since() { awk -v a="$1" -v b="$(now)" 'BEGIN{printf "%.1f", b-a}'; }

# Map stand-ins. Keys are table names, which are identifier-safe (b_narrow_1 …).
# Map names carry the phase number so no value leaks from one phase into the next.
kv_set() { printf -v "kv_$1__$2" '%s' "$3"; }
kv_get() { local v="kv_$1__$2"; echo "${!v:-}"; }

shape_of() { case "$1" in b_narrow_*) echo narrow;; b_wide_*) echo wide;; b_lob_*) echo lob;; esac; }

pg_ddl() {
  local t="$1"
  case "$(shape_of "$t")" in
    narrow) echo "CREATE TABLE $t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              account_id integer NOT NULL, status smallint NOT NULL, amount numeric(18,4) NOT NULL,
              created_at timestamp(6) NOT NULL, code varchar(32) NOT NULL)";;
    wide)   echo "CREATE TABLE $t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              c01 varchar(255), c02 varchar(255), c03 varchar(255), c04 varchar(255), c05 varchar(255),
              c06 varchar(255), c07 varchar(255), c08 varchar(255), c09 varchar(255), c10 varchar(255),
              note text, amount numeric(18,4), created_at timestamp(6))";;
    lob)    echo "CREATE TABLE $t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              label varchar(64) NOT NULL, c_payload bytea)";;
  esac
}

# ADR-0002 planned transfer bytes, from the same statistics the estimator reads
est_bytes() {
  mysqlq "SELECT ROUND(1.5 * GREATEST(data_length, $2 * avg_row_length)), data_length
          FROM information_schema.tables WHERE table_schema='dbx_src' AND table_name='$1'" | tr -d '\r'
}

put_source() {
  local tag="$1" t="$2" rows="$ORDINARY_BATCH_MAX_ROWS" buf=0
  [ "$(shape_of "$t")" = lob ] && { rows="$LOB_BATCH_MAX_ROWS"; buf="$LOB_MAX_BUFFER"; }
  local src_env='"producer.override.max.request.size": 26214400, "producer.override.buffer.memory": 134217728,'
  [ "$ORDINARY_OVERRIDES" = 0 ] && [ "$(shape_of "$t")" != lob ] && src_env=''
  put_connector "tp-$tag-src-$t" <<JSON
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "connection.url": "$(mysql_url "$rows")",
  "connection.user": "dbx", "connection.password": "dbx",
  "mode": "incrementing", "incrementing.column.name": "id",
  "table.whitelist": "$t",
  "topic.prefix": "dbx.tp.$tag.",
  "poll.interval.ms": 5000, "tasks.max": 1,
  "batch.max.rows": $rows, "max.buffer.size": $buf,
  $src_env
  "producer.override.compression.type": "zstd",
  "producer.override.max.in.flight.requests.per.connection": 1
}
JSON
}

put_sink() {
  local tag="$1" t="$2" poll="$ORDINARY_POLL_RECORDS"
  [ "$(shape_of "$t")" = lob ] && poll=1
  local sink_env='"consumer.override.max.partition.fetch.bytes": 26214400, "consumer.override.fetch.max.bytes": 52428800, "consumer.override.max.poll.interval.ms": 900000,'
  [ "$ORDINARY_OVERRIDES" = 0 ] && [ "$(shape_of "$t")" != lob ] && sink_env=''
  put_connector "tp-$tag-sink-$t" <<JSON
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
  "connection.url": "jdbc:postgresql://postgres:5432/dbx_target",
  "connection.user": "dbx", "connection.password": "dbx",
  "topics": "dbx.tp.$tag.$t", "table.name.format": "$t",
  "auto.create": "false", "auto.evolve": "false",
  "insert.mode": "insert", "pk.mode": "none", "delete.enabled": "false",
  "quote.sql.identifiers": "always",
  "errors.tolerance": "none", "tasks.max": 1,
  $sink_env
  "consumer.override.max.poll.records": $poll
}
JSON
}

cleanup_all() {
  local c
  for c in $(curl -sS "$CONNECT/connectors" | jq -r '.[] | select(startswith("tp-"))'); do
    delete_connector "$c"
  done
  sleep 2
  for c in $(dc exec -T kafka /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list \
             2>/dev/null | tr -d '\r' | grep '^dbx\.tp\.'); do
    delete_topic "$c"
  done
  for c in $(psqlq "SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'b\_%'"); do
    psqlq "DROP TABLE IF EXISTS $c" >/dev/null
  done
}

failed_connectors() {
  curl -sS "$CONNECT/connectors?expand=status" | jq -r 'to_entries[]
    | select(.key | startswith("tp-"))
    | select([.value.status.connector.state, .value.status.tasks[]?.state] | index("FAILED"))
    | .key'
}

# Every phase starts on a freshly restarted worker. A worker that once hit OutOfMemoryError keeps
# answering REST, but its offsets-topic reader thread can be dead: every new Source then blocks
# forever in start() reading offsets (observed: 90 min per phase with zero records).
# A restart also gives each phase the same empty heap.
fresh_worker() {
  log "restarting Connect for a fresh worker"
  dc restart connect >> "$(art)/run.log" 2>&1
  local i
  for i in $(seq 1 120); do
    curl -sf "$CONNECT/connectors" >/dev/null && { sleep 10; return 0; }   # 10 s for group join
    sleep 2
  done
  log "Connect did not come back after restart"; exit 1
}

record_env() {
  {
    echo "## host"
    if command -v sysctl >/dev/null; then
      sysctl -n hw.model machdep.cpu.brand_string hw.ncpu hw.memsize 2>/dev/null
      sw_vers -productVersion 2>/dev/null
    fi
    uptime
    echo "## docker"
    docker info --format '{{.OperatingSystem}} {{.ServerVersion}}, {{.NCPU}} vCPU, {{.MemTotal}} B'
    echo "## images (docker-compose.yml; Connect is built FROM the cp-kafka-connect tag in connect/Dockerfile)"
    grep -E '^\s+image:' "$ENV_DIR/docker-compose.yml" | sed 's/#.*//'
    grep -E '^FROM' "$ENV_DIR/connect/Dockerfile"
    echo "## worker overrides (docker-compose.yml)"
    grep -E 'CONNECT_(CONSUMER|PRODUCER)_|KAFKA_HEAP_OPTS' "$ENV_DIR/docker-compose.yml" | sed 's/#.*//'
    echo "## database limits"
    echo "mysql max_connections=$(mysqlq 'SELECT @@max_connections' | tr -d '\r')" \
         "innodb_buffer_pool_size=$(mysqlq 'SELECT @@innodb_buffer_pool_size' | tr -d '\r')"
    echo "postgres max_connections=$(psqlq 'SHOW max_connections')" \
         "shared_buffers=$(psqlq 'SHOW shared_buffers')" "max_wal_size=$(psqlq 'SHOW max_wal_size')"
  } > "$(art)/env.txt" 2>&1
}

# ADR-0002 default budgets on this machine. Each single-table box holds one Source and
# one Sink task, and each task holds one database connection.
budget() { local b=$(( $1 / 10 )); [ $b -lt 4 ] && b=4; [ $b -gt 20 ] && b=20; echo $(( b - 2 )); }
record_budgets() {
  local ncpu myc pgc tasks src tgt lim=10
  ncpu=$(docker info --format '{{.NCPU}}')
  myc=$(mysqlq 'SELECT @@max_connections' | tr -d '\r')
  pgc=$(psqlq 'SHOW max_connections')
  tasks=$(( 2 * ncpu )); src=$(budget "$myc"); tgt=$(budget "$pgc")
  [ $(( tasks / 2 )) -lt $lim ] && lim=$(( tasks / 2 ))
  [ "$src" -lt $lim ] && lim=$src
  [ "$tgt" -lt $lim ] && lim=$tgt
  ADMIT=$lim
  finding "ADR-0002 default budgets here: Connect tasks $tasks (2 x $ncpu vCPU), boxes 10, source connections $src (max_connections $myc), target connections $tgt (max_connections $pgc) → at most **$ADMIT** concurrent single-table boxes"
}

PH=0
# run_phase <tag> <table...>: start every table at once, sample until all are written
run_phase() {
  local tag="$1"; shift
  local t m
  local tsv="$(art)/timeline-$tag.tsv" res="$(art)/results-$tag.tsv"
  PH=$((PH+1)); m="p$PH"
  cleanup_all
  fresh_worker
  for t in "$@"; do
    kv_set "${m}_rows" "$t" "$(mysqlq "SELECT COUNT(*) FROM $t" | tr -d '\r')"
    local e d; read -r e d <<<"$(est_bytes "$t" "$(kv_get "${m}_rows" "$t")")"
    kv_set "${m}_est" "$t" "$e"; kv_set "${m}_dlen" "$t" "$d"
    psqlq "$(pg_ddl "$t")" >> "$(art)/run.log" 2>&1
    create_topic "dbx.tp.$tag.$t"
  done
  log "phase $tag: $*"

  local T0; T0=$(now)
  for t in "$@"; do put_sink "$tag" "$t"; done      # Sink before Source (ADR-0009)
  for t in "$@"; do put_source "$tag" "$t"; done

  printf 't\ttable\ttopic_end\tpg_inserted\n' > "$tsv"
  local left=$# i=0 el topic off rel ins rows end n tot last_tot=-1 last_prog=0
  while [ "$left" -gt 0 ]; do
    sleep "$SAMPLE_S"; i=$((i+1)); el=$(since "$T0")
    while IFS=: read -r topic _ off; do kv_set "${m}_end" "${topic#dbx.tp.$tag.}" "$off"; done < <(
      dc exec -T kafka /opt/kafka/bin/kafka-get-offsets.sh --bootstrap-server localhost:9092 \
        --topic "dbx\\.tp\\.$tag\\..*" --time -1 2>/dev/null | tr -d '\r')
    while IFS='|' read -r rel ins; do kv_set "${m}_ins" "$rel" "$ins"; done < <(
      psqlq "SELECT relname, n_tup_ins FROM pg_stat_user_tables WHERE relname LIKE 'b\_%'")
    left=0; tot=0
    for t in "$@"; do
      rows=$(kv_get "${m}_rows" "$t"); end=$(kv_get "${m}_end" "$t"); ins=$(kv_get "${m}_ins" "$t")
      printf '%s\t%s\t%s\t%s\n' "$el" "$t" "${end:-0}" "${ins:-0}" >> "$tsv"
      tot=$(( tot + ${end:-0} + ${ins:-0} ))
      [ -z "$(kv_get "${m}_srcdone" "$t")" ] && [ "${end:-0}" -ge "$rows" ] && kv_set "${m}_srcdone" "$t" "$el"
      if [ -z "$(kv_get "${m}_sinkdone" "$t")" ] && [ "${ins:-0}" -ge "$rows" ]; then
        n=$(psqlq "SELECT COUNT(*) FROM $t")
        if [ "$n" -ge "$rows" ]; then
          kv_set "${m}_sinkdone" "$t" "$(since "$T0")"; log "$t written at $(kv_get "${m}_sinkdone" "$t")s"
        fi
      fi
      [ -z "$(kv_get "${m}_sinkdone" "$t")" ] && left=$((left+1))
    done
    if [ $((i % 10)) -eq 0 ]; then
      # Connect heap over time: the evidence for how much each concurrent box costs
      dc exec -T connect jcmd 1 GC.heap_info 2>/dev/null | awk -v t="$el" '/heap/ {print t "\t" $0; exit}' \
        >> "$(art)/heap-$tag.tsv"
      docker stats --no-stream --format '{{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}' \
        | sed "s/^/$el	/" >> "$(art)/docker-stats-$tag.tsv"
      local f; f=$(failed_connectors)
      if [ -n "$f" ]; then
        for t in $f; do snapshot_status "$t" "$tag"; done
        dc exec -T connect jcmd 1 GC.class_histogram 2>/dev/null | head -25 > "$(art)/histogram-$tag.txt"
        capture_connect_log "$tag"
        finding "**phase $tag aborted**: connector(s) FAILED: $(echo $f)"
        return 1
      fi
    fi
    if [ "$tot" != "$last_tot" ]; then last_tot=$tot; last_prog=$el; fi
    if [ "$left" -gt 0 ] && awk -v e="$el" -v p="$last_prog" -v s="$STALL_S" 'BEGIN{exit !(e-p>s)}'; then
      finding "**phase $tag stalled**: no topic or target progress for ${STALL_S}s (at ${el}s)"
      capture_connect_log "$tag"; return 1
    fi
    if awk -v e="$el" -v x="$PHASE_TIMEOUT_S" 'BEGIN{exit !(e>x)}'; then
      finding "**phase $tag timed out** after ${PHASE_TIMEOUT_S}s with $left table(s) unwritten"
      capture_connect_log "$tag"; return 1
    fi
  done

  PHASE_MAKESPAN=$(since "$T0")
  printf 'table\tshape\trows\tdata_length\test_bytes\ttopic_bytes\tsrc_done_s\tsink_done_s\test_MiB_s\tdata_MiB_s\trows_s\n' > "$res"
  for t in "$@"; do
    local tb; tb=$(dc exec -T kafka du -sk "/var/lib/kafka/data/dbx.tp.$tag.$t-0" 2>/dev/null | awk '{print $1*1024}')
    awk -v t="$t" -v s="$(shape_of "$t")" -v r="$(kv_get "${m}_rows" "$t")" -v d="$(kv_get "${m}_dlen" "$t")" \
        -v e="$(kv_get "${m}_est" "$t")" -v tb="${tb:-0}" -v sd="$(kv_get "${m}_srcdone" "$t")" \
        -v kd="$(kv_get "${m}_sinkdone" "$t")" 'BEGIN{
      if (sd == "") sd = "NA"
      printf "%s\t%s\t%d\t%d\t%d\t%d\t%s\t%s\t%.2f\t%.2f\t%.0f\n", t, s, r, d, e, tb, sd, kd,
        e/kd/1048576, d/kd/1048576, r/kd }' >> "$res"
  done
  capture_connect_log "$tag" 200
  return 0
}

preflight
for t in $SINGLE_TABLES; do
  [ "$(mysqlq "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='dbx_src' AND table_name='$t'" | tr -d '\r')" = 1 ] \
    || { log "missing $t: run ./e2e/bulk/seed-bulk.sh first"; exit 1; }
done
record_env
record_budgets
finding "Source (every table): \`mode=incrementing\` (ADR-0001), \`tasks.max=1\`, \`poll.interval.ms=5000\`; ordinary tables \`batch.max.rows=$ORDINARY_BATCH_MAX_ROWS\` (connector default) and \`max.buffer.size=0\` (default); large-record table \`batch.max.rows=$LOB_BATCH_MAX_ROWS\`, \`max.buffer.size=$LOB_MAX_BUFFER\`; MySQL URL $( [ "$CURSOR_FETCH" = 1 ] && echo "\`useCursorFetch=true\`, \`defaultFetchSize\` = the table's batch.max.rows" || echo "without cursor fetch (whole result set buffered)"); ADR-0003 producer overrides (zstd, 25 MiB request, 128 MiB buffer, in-flight 1)"
finding "Sink: \`insert.mode=insert\`, \`pk.mode=none\`, \`quote.sql.identifiers=always\` (plan §7.4); \`batch.size\` unset → connector default 3000; \`consumer.override.max.poll.records\` = **$ORDINARY_POLL_RECORDS** for ordinary tables, **1** for the large-record table (ADR-0003); worker-level default is 1"

[ "$ORDINARY_OVERRIDES" = 0 ] && finding "**Variant ORDINARY_OVERRIDES=0**: ordinary connectors run without ADR-0003's size overrides (producer max.request.size / buffer.memory, consumer max.partition.fetch.bytes / fetch.max.bytes / max.poll.interval.ms → client defaults); the large-record table keeps them"

if [[ " $PHASES " == *" single "* ]]; then
  for t in $SINGLE_TABLES; do
    if run_phase "single-$(shape_of "$t")" "$t"; then
      finding "single stream \`$t\`: $(tail -1 "$(art)/results-single-$(shape_of "$t").tsv" \
        | awk -F'\t' '{printf "%s rows in %ss (source read done at %ss) → **%s MiB/s estimator bytes**, %s MiB/s DATA_LENGTH, %s rows/s", $3, $8, $7, $9, $10, $11}')"
    fi
  done
fi

if [[ " $PHASES " == *" concurrent "* ]]; then
  CONC=( $(mysqlq "SELECT table_name FROM information_schema.tables WHERE table_schema='dbx_src'
                   AND table_name LIKE 'b\\_%' ORDER BY table_name" | tr -d '\r') )
  [ "${#CONC[@]}" -gt "$ADMIT" ] && log "WARNING: ${#CONC[@]} tables exceed the $ADMIT-box admission limit; the phase starts them all anyway"
  if run_phase concurrent "${CONC[@]}"; then
    res="$(art)/results-concurrent.tsv"
    # Aggregate rate over the whole run, and over the window where every stream was still
    # running (before the first table finished): the tail after that is the minimum window's job.
    first=$(awk -F'\t' 'NR>1{print $8}' "$res" | sort -n | head -1)
    all_active=$(awk -F'\t' -v f="$first" '
      FNR==NR { if (FNR>1) { rows[$1]=$3; est[$1]=$5 } next }
      FNR>1 && $1<=f { ins[$2]=$4; last=$1 }
      END { for (t in ins) b += (ins[t] > rows[t] ? rows[t] : ins[t]) / rows[t] * est[t]; printf "%.2f", b/last/1048576 }' \
      "$res" "$(art)/timeline-concurrent.tsv")
    total=$(awk -F'\t' -v m="$PHASE_MAKESPAN" 'NR>1{e+=$5; d+=$4} END{printf "%.2f MiB/s estimator bytes (%.2f MiB/s DATA_LENGTH) over %.0f MiB in %ss", e/m/1048576, d/m/1048576, e/1048576, m}' "$res")
    finding "concurrent (${#CONC[@]} boxes): whole run **$total**; all-streams-active window (first ${first}s) **${all_active} MiB/s** estimator bytes"
    finding "per-table finish times (s): $(awk -F'\t' 'NR>1{printf "%s=%s ", $1, $8}' "$res")"
  fi
fi

[ "${KEEP:-0}" = 1 ] || cleanup_all
log "S9 done, artifacts in $(art)"
