#!/usr/bin/env bash
# S9: reference throughput band (ticket #63, map #1; feeds ADR-0019).
#
# Two measurements on the bulk dataset from e2e/bulk/seed-bulk.sh:
#   single      one table per shape, run alone: one Source task, one Sink task, nothing else
#               on the worker. Yields single-stream throughput, which feeds 窗口下限
#               (minimum window).
#   concurrent  every b_* table at once, one box per table. All of them fit ADR-0002's default
#               admission budgets (see FINDINGS), so rolling admission would start them all
#               immediately. Yields aggregate throughput, which feeds 预估耗时 (duration estimate).
#
# Throughput is reported in the estimator's own unit: ADR-0002 "planned transfer bytes"
# = 1.5 * max(DATA_LENGTH, exact rows * AVG_ROW_LENGTH). The estimator divides those bytes
# by the band, so a band in any other unit would be off by the 1.5x factor and the
# DATA_LENGTH vs payload gap. DATA_LENGTH/s and rows/s are recorded alongside.
#
# The clock starts before the first connector PUT and stops when the target table holds every
# source row (pg_stat n_tup_ins, confirmed with COUNT(*)). That is end-to-end time, the way
# a DBA experiences it, not source read speed.
#
#   ./e2e/bulk/seed-bulk.sh && ./e2e/run-all.sh s9     # both phases
#   PHASES=single ./e2e/run-all.sh s9                   # one phase only
#
# Connector settings follow docs/technical-plan.md §7.4 and ADR-0003. Anything that doc
# leaves unset stays at the connector default and is listed in FINDINGS.

source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
init_scenario s9 "reference throughput band"

PHASES="${PHASES:-single concurrent}"
SINGLE_TABLES="${SINGLE_TABLES:-b_narrow_1 b_wide_1 b_lob_1}"
SAMPLE_S="${SAMPLE_S:-2}"
PHASE_TIMEOUT_S="${PHASE_TIMEOUT_S:-5400}"
ORDINARY_POLL_RECORDS=500     # Kafka's own default; ADR-0003 keeps poll=1 for large-record tables only

# EPOCHREALTIME needs bash 5; fall back to whole seconds
now() { if [ -n "${EPOCHREALTIME:-}" ]; then echo "${EPOCHREALTIME/,/.}"; else date +%s; fi; }
since() { awk -v a="$1" -v b="$(now)" 'BEGIN{printf "%.1f", b-a}'; }

shape_of() { case "$1" in b_narrow_*) echo narrow;; b_wide_*) echo wide;; b_lob_*) echo lob;; esac; }

pg_ddl() {
  local t="$1"
  case "$(shape_of "$t")" in
    narrow) echo "CREATE TABLE $t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              account_id integer NOT NULL, status smallint NOT NULL, amount numeric(18,4) NOT NULL,
              created_at timestamp(6) NOT NULL, code varchar(32) NOT NULL)";;
    wide)   echo "CREATE TABLE $t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              c01 varchar(255), c02 varchar(255), c03 varchar(255), c04 varchar(255), c05 varchar(255),
              c06 varchar(255), c07 varchar(255), c08 varchar(255), c09 varchar(255), c10 varchar(255),
              note text, amount numeric(18,4), created_at timestamp(6))";;
    lob)    echo "CREATE TABLE $t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              label varchar(64) NOT NULL, c_payload bytea)";;
  esac
}

# ADR-0002 planned transfer bytes, from the same statistics the estimator reads
est_bytes() {
  mysqlq "SELECT ROUND(1.5 * GREATEST(data_length, $2 * avg_row_length)), data_length
          FROM information_schema.tables WHERE table_schema='dbx_src' AND table_name='$1'" | tr -d '\r'
}

put_source() {
  local tag="$1" t="$2"
  put_connector "tp-$tag-src-$t" <<JSON
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
  "connection.url": "jdbc:mysql://mysql:3306/dbx_src?useSSL=false&allowPublicKeyRetrieval=true",
  "connection.user": "dbx", "connection.password": "dbx",
  "mode": "incrementing", "incrementing.column.name": "id",
  "table.whitelist": "$t",
  "topic.prefix": "dbx.tp.$tag.",
  "poll.interval.ms": 5000, "tasks.max": 1,
  "producer.override.max.request.size": 26214400,
  "producer.override.buffer.memory": 134217728,
  "producer.override.compression.type": "zstd",
  "producer.override.max.in.flight.requests.per.connection": 1
}
JSON
}

put_sink() {
  local tag="$1" t="$2" poll="$ORDINARY_POLL_RECORDS"
  [ "$(shape_of "$t")" = lob ] && poll=1
  put_connector "tp-$tag-sink-$t" <<JSON
{
  "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
  "connection.url": "jdbc:postgresql://postgres:5432/dbx_target",
  "connection.user": "dbx", "connection.password": "dbx",
  "topics": "dbx.tp.$tag.$t", "table.name.format": "$t",
  "auto.create": "false", "auto.evolve": "false",
  "insert.mode": "insert", "pk.mode": "none", "delete.enabled": "false",
  "quote.sql.identifiers": "always",
  "errors.tolerance": "none", "tasks.max": 1,
  "consumer.override.max.poll.records": $poll,
  "consumer.override.max.partition.fetch.bytes": 26214400,
  "consumer.override.fetch.max.bytes": 52428800,
  "consumer.override.max.poll.interval.ms": 900000
}
JSON
}

cleanup_all() {
  local c
  for c in $(curl -sS "$CONNECT/connectors" | jq -r '.[] | select(startswith("tp-"))'); do
    delete_connector "$c"
  done
  sleep 2
  for c in $(dc exec -T kafka /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list \
             2>/dev/null | tr -d '\r' | grep '^dbx\.tp\.'); do
    delete_topic "$c"
  done
  for c in $(psqlq "SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'b\_%'"); do
    psqlq "DROP TABLE IF EXISTS $c" >/dev/null
  done
}

failed_connectors() {
  curl -sS "$CONNECT/connectors?expand=status" | jq -r 'to_entries[]
    | select(.key | startswith("tp-"))
    | select([.value.status.connector.state, .value.status.tasks[]?.state] | index("FAILED"))
    | .key'
}

record_env() {
  {
    echo "## host"
    if command -v sysctl >/dev/null; then
      sysctl -n hw.model machdep.cpu.brand_string hw.ncpu hw.memsize 2>/dev/null
      sw_vers -productVersion 2>/dev/null
    fi
    echo "## docker"
    docker info --format '{{.OperatingSystem}} {{.ServerVersion}}, {{.NCPU}} vCPU, {{.MemTotal}} B'
    echo "## images"
    dc images --format '{{.Repository}}:{{.Tag}}' 2>/dev/null || dc images
    echo "## worker overrides (docker-compose.yml)"
    grep -E 'CONNECT_(CONSUMER|PRODUCER)_|KAFKA_HEAP_OPTS' "$ENV_DIR/docker-compose.yml" | sed 's/#.*//'
    echo "## database limits"
    echo "mysql max_connections=$(mysqlq 'SELECT @@max_connections' | tr -d '\r')" \
         "innodb_buffer_pool_size=$(mysqlq 'SELECT @@innodb_buffer_pool_size' | tr -d '\r')"
    echo "postgres max_connections=$(psqlq 'SHOW max_connections')" \
         "shared_buffers=$(psqlq 'SHOW shared_buffers')" "max_wal_size=$(psqlq 'SHOW max_wal_size')"
  } > "$(art)/env.txt" 2>&1
}

# ADR-0002 default budgets on this machine. Each single-table box holds one Source and
# one Sink task, and each task holds one database connection.
record_budgets() {
  local ncpu myc pgc
  ncpu=$(docker info --format '{{.NCPU}}')
  myc=$(mysqlq 'SELECT @@max_connections' | tr -d '\r')
  pgc=$(psqlq 'SHOW max_connections')
  budget() { local b=$(( $1 / 10 )); [ $b -lt 4 ] && b=4; [ $b -gt 20 ] && b=20; echo $(( b - 2 )); }
  local tasks=$(( 2 * ncpu )) src; src=$(budget "$myc"); local tgt; tgt=$(budget "$pgc")
  local boxes=10
  local lim=$boxes
  [ $(( tasks / 2 )) -lt $lim ] && lim=$(( tasks / 2 ))
  [ "$src" -lt $lim ] && lim=$src
  [ "$tgt" -lt $lim ] && lim=$tgt
  ADMIT=$lim
  finding "ADR-0002 default budgets here: Connect tasks $tasks (2 x $ncpu vCPU), boxes 10, source connections $src (max_connections $myc), target connections $tgt (max_connections $pgc) → at most **$ADMIT** concurrent single-table boxes"
}

# run_phase <tag> <table...>: start every table at once, sample until all are written
run_phase() {
  local tag="$1"; shift
  local tables=("$@") t
  local tsv="$(art)/timeline-$tag.tsv" res="$(art)/results-$tag.tsv"
  declare -A ROWS EST DLEN SRC_DONE SINK_DONE
  cleanup_all
  for t in "${tables[@]}"; do
    ROWS[$t]=$(mysqlq "SELECT COUNT(*) FROM $t" | tr -d '\r')
    read -r EST[$t] DLEN[$t] <<<"$(est_bytes "$t" "${ROWS[$t]}")"
    psqlq "$(pg_ddl "$t")" >> "$(art)/run.log" 2>&1
    create_topic "dbx.tp.$tag.$t"
  done
  log "phase $tag: ${tables[*]}"

  local T0; T0=$(now)
  for t in "${tables[@]}"; do put_sink "$tag" "$t"; done      # Sink before Source (ADR-0009)
  for t in "${tables[@]}"; do put_source "$tag" "$t"; done

  printf 't\ttable\ttopic_end\tpg_inserted\n' > "$tsv"
  local left=${#tables[@]} i=0 el
  while [ "$left" -gt 0 ]; do
    sleep "$SAMPLE_S"; i=$((i+1)); el=$(since "$T0")
    declare -A END=() INS=()
    while IFS=: read -r topic _ off; do END[${topic#dbx.tp.$tag.}]=$off; done < <(
      dc exec -T kafka /opt/kafka/bin/kafka-get-offsets.sh --bootstrap-server localhost:9092 \
        --topic "dbx\\.tp\\.$tag\\..*" --time -1 2>/dev/null | tr -d '\r')
    while IFS='|' read -r rel ins; do INS[$rel]=$ins; done < <(
      psqlq "SELECT relname, n_tup_ins FROM pg_stat_user_tables WHERE relname LIKE 'b\_%'")
    left=0
    for t in "${tables[@]}"; do
      printf '%s\t%s\t%s\t%s\n' "$el" "$t" "${END[$t]:-0}" "${INS[$t]:-0}" >> "$tsv"
      [ -z "${SRC_DONE[$t]:-}" ] && [ "${END[$t]:-0}" -ge "${ROWS[$t]}" ] && SRC_DONE[$t]=$el
      if [ -z "${SINK_DONE[$t]:-}" ] && [ "${INS[$t]:-0}" -ge "${ROWS[$t]}" ] \
         && [ "$(psqlq "SELECT COUNT(*) FROM $t")" -ge "${ROWS[$t]}" ]; then
        SINK_DONE[$t]=$(since "$T0"); log "$t written at ${SINK_DONE[$t]}s"
      fi
      [ -z "${SINK_DONE[$t]:-}" ] && left=$((left+1))
    done
    if [ $((i % 10)) -eq 0 ]; then
      docker stats --no-stream --format '{{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}' \
        | sed "s/^/$el\t/" >> "$(art)/docker-stats-$tag.tsv"
      local f; f=$(failed_connectors)
      if [ -n "$f" ]; then
        for t in $f; do snapshot_status "$t" "$tag"; done
        capture_connect_log "$tag"
        finding "**phase $tag aborted**: connector(s) FAILED: $(echo $f)"
        return 1
      fi
    fi
    if awk -v e="$el" -v m="$PHASE_TIMEOUT_S" 'BEGIN{exit !(e>m)}'; then
      finding "**phase $tag timed out** after ${PHASE_TIMEOUT_S}s with $left table(s) unwritten"
      capture_connect_log "$tag"; return 1
    fi
  done

  local makespan; makespan=$(since "$T0")
  printf 'table\tshape\trows\tdata_length\test_bytes\ttopic_bytes\tsrc_done_s\tsink_done_s\test_MiB_s\tdata_MiB_s\trows_s\n' > "$res"
  for t in "${tables[@]}"; do
    local tb; tb=$(dc exec -T kafka du -sk "/var/lib/kafka/data/dbx.tp.$tag.$t-0" 2>/dev/null | awk '{print $1*1024}')
    awk -v t="$t" -v s="$(shape_of "$t")" -v r="${ROWS[$t]}" -v d="${DLEN[$t]}" -v e="${EST[$t]}" \
        -v tb="${tb:-0}" -v sd="${SRC_DONE[$t]:-NA}" -v kd="${SINK_DONE[$t]}" 'BEGIN{
      printf "%s\t%s\t%d\t%d\t%d\t%d\t%s\t%s\t%.2f\t%.2f\t%.0f\n", t, s, r, d, e, tb, sd, kd,
        e/kd/1048576, d/kd/1048576, r/kd }' >> "$res"
  done
  capture_connect_log "$tag" 200
  PHASE_MAKESPAN=$makespan
  return 0
}

preflight
for t in $SINGLE_TABLES; do
  [ "$(mysqlq "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='dbx_src' AND table_name='$t'" | tr -d '\r')" = 1 ] \
    || { log "missing $t: run ./e2e/bulk/seed-bulk.sh first"; exit 1; }
done
record_env
record_budgets
finding "Source (every table): \`mode=incrementing\` (ADR-0001), \`tasks.max=1\`, \`poll.interval.ms=5000\`; \`batch.max.rows\` unset → connector default 100; MySQL URL without cursor fetch; ADR-0003 producer overrides (zstd, 25 MiB request, 128 MiB buffer, in-flight 1)"
finding "Sink: \`insert.mode=insert\`, \`pk.mode=none\`, \`quote.sql.identifiers=always\` (plan §7.4); \`batch.size\` unset → connector default 3000; \`consumer.override.max.poll.records\` = **$ORDINARY_POLL_RECORDS** for ordinary tables, **1** for the large-record table (ADR-0003); worker-level default is 1"

if [[ " $PHASES " == *" single "* ]]; then
  for t in $SINGLE_TABLES; do
    if run_phase "single-$(shape_of "$t")" "$t"; then
      finding "single stream \`$t\`: $(tail -1 "$(art)/results-single-$(shape_of "$t").tsv" \
        | awk -F'\t' '{printf "%s rows in %ss (source read done at %ss) → **%s MiB/s estimator bytes**, %s MiB/s DATA_LENGTH, %s rows/s", $3, $8, $7, $9, $10, $11}')"
    fi
  done
fi

if [[ " $PHASES " == *" concurrent "* ]]; then
  CONC=( $(mysqlq "SELECT table_name FROM information_schema.tables WHERE table_schema='dbx_src'
                   AND table_name LIKE 'b\\_%' ORDER BY table_name" | tr -d '\r') )
  [ "${#CONC[@]}" -gt "$ADMIT" ] && log "WARNING: ${#CONC[@]} tables exceed the $ADMIT-box admission limit; the phase starts them all anyway"
  if run_phase concurrent "${CONC[@]}"; then
    res="$(art)/results-concurrent.tsv"
    # Aggregate rate over the whole run, and over the window where every stream was still
    # running (before the first table finished): the tail after that is the minimum window's job.
    first=$(awk -F'\t' 'NR>1{print $8}' "$res" | sort -n | head -1)
    all_active=$(awk -F'\t' -v f="$first" '
      FNR==NR { if (FNR>1) { rows[$1]=$3; est[$1]=$5 } next }
      FNR>1 && $1<=f { ins[$2]=$4; last=$1 }
      END { for (t in ins) b += (ins[t] > rows[t] ? rows[t] : ins[t]) / rows[t] * est[t]; printf "%.2f", b/last/1048576 }' \
      "$res" "$(art)/timeline-concurrent.tsv")
    total=$(awk -F'\t' -v m="$PHASE_MAKESPAN" 'NR>1{e+=$5; d+=$4} END{printf "%.2f MiB/s estimator bytes (%.2f MiB/s DATA_LENGTH) over %.0f MiB in %ss", e/m/1048576, d/m/1048576, e/1048576, m}' "$res")
    finding "concurrent (${#CONC[@]} boxes): whole run **$total**; all-streams-active window (first ${first}s) **${all_active} MiB/s** estimator bytes"
    finding "per-table finish times (s): $(awk -F'\t' 'NR>1{printf "%s=%s ", $1, $8}' "$res")"
  fi
fi

[ "${KEEP:-0}" = 1 ] || cleanup_all
log "S9 done, artifacts in $(art)"
